spring:
  application:
    name: pal-points

  devtools:
    restart:
      enabled: false
  datasource:
    url: jdbc:postgresql://aws-1-us-east-1.pooler.supabase.com:5432/postgres?sslmode=require
    username: postgres.ypqcubzwnqewqsvxpywf
    password: xcvNd2WrRAwniyq2
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql:
          trueql: true